import Foundation
import HavenCore
import os

private let log = Logger(subsystem: "com.haven", category: "InstallStepExecutor")

/// Executes resolved install steps with automatic rollback on failure.
///
/// Each step is executed in order. As steps complete, rollback closures are
/// recorded. If any step fails, all completed steps are rolled back in
/// reverse order, then the original error is rethrown.
///
/// ## Secret Generation
///
/// The `generateSecret` action produces cryptographic random bytes and
/// returns them via the `generatedSecrets` dictionary on the result.
/// The caller is responsible for injecting these into the template context
/// before expanding subsequent templates (e.g. `writeFile` content).
///
/// ## Path Safety
///
/// All resolved paths are validated to stay inside `serviceRoot`.
/// Path traversal (`..`) is rejected.
public struct InstallStepExecutor: Sendable {

    private nonisolated(unsafe) let fileManager: FileManager

    public init(fileManager: FileManager = .default) {
        self.fileManager = fileManager
    }

    /// The result of executing an install block.
    public struct Result: Sendable {
        /// Secrets generated by `generateSecret` steps.
        /// Key = variable name (from `path`), value = encoded string.
        public let generatedSecrets: [String: String]
    }

    /// Execute all steps in an install block.
    ///
    /// Steps that produce secrets (via `generateSecret`) are collected and
    /// their values are used to expand subsequent step templates. This means
    /// a `writeFile` step can reference `${api_key}` if a prior
    /// `generateSecret` step defined it.
    ///
    /// - Parameters:
    ///   - block: The resolved install block (templates already expanded for
    ///     non-secret variables).
    ///   - serviceRoot: The service's root directory. All paths must resolve
    ///     inside this directory unless listed in `allowedExternalPaths`.
    ///   - templateContext: The template context for expanding secret
    ///     variables into subsequent steps.
    ///   - allowedExternalPaths: Absolute paths outside the service root that
    ///     are permitted (e.g. user-configured content directories like ~/Music).
    /// - Returns: The execution result containing any generated secrets.
    /// - Throws: ``InstallStepError`` if any step fails. All prior steps
    ///   are rolled back before the error is thrown.
    public func execute(
        block: InstallBlock,
        serviceRoot: URL,
        templateContext: TemplateContext? = nil,
        allowedExternalPaths: Set<String> = []
    ) throws -> Result {
        let rootPath = serviceRoot.standardizedFileURL.path
        var rollbackActions: [() -> Void] = []
        var secrets: [String: String] = [:]

        // Build a mutable context that accumulates generated secrets
        var currentContext = templateContext ?? TemplateContext(values: [:])

        func rollback(_ error: Error) throws -> Never {
            log.warning("[install-steps] Rolling back \(rollbackActions.count) steps...")
            for action in rollbackActions.reversed() {
                action()
            }
            throw error
        }

        for (index, rawStep) in block.steps.enumerated() {
            // Re-expand the step with current context (includes accumulated secrets)
            let step = currentContext.expand(rawStep)

            log.info("[install-steps] Step \(index + 1)/\(block.steps.count): \(step.action.rawValue) path=\(step.path)")

            // ifNotExists guard: skip if the target already exists.
            // For generateSecret, check if the variable is already in context.
            if step.ifNotExists {
                if step.action == .generateSecret {
                    if currentContext.values[step.path] != nil {
                        log.info("[install-steps] Skipping (ifNotExists): secret '\(step.path)' already in context")
                        continue
                    }
                } else {
                    let targetURL = URL(fileURLWithPath: step.path)
                    if fileManager.fileExists(atPath: targetURL.path) {
                        log.info("[install-steps] Skipping (ifNotExists): \(step.path) already exists")
                        continue
                    }
                }
            }

            do {
                switch step.action {
                case .mkdir:
                    let url = try validatedURL(path: step.path, root: rootPath, allowedExternalPaths: allowedExternalPaths)
                    try executeMkdir(url: url, rollback: &rollbackActions)

                case .copy:
                    guard let source = step.source else {
                        throw InstallStepError.missingSource(
                            action: step.action.rawValue, path: step.path
                        )
                    }
                    let sourceURL = try validatedURL(path: source, root: rootPath, allowedExternalPaths: allowedExternalPaths)
                    let destURL = try validatedURL(path: step.path, root: rootPath, allowedExternalPaths: allowedExternalPaths)
                    try executeCopy(
                        source: sourceURL, destination: destURL,
                        rollback: &rollbackActions
                    )

                case .move:
                    guard let source = step.source else {
                        throw InstallStepError.missingSource(
                            action: step.action.rawValue, path: step.path
                        )
                    }
                    let sourceURL = try validatedURL(path: source, root: rootPath, allowedExternalPaths: allowedExternalPaths)
                    let destURL = try validatedURL(path: step.path, root: rootPath, allowedExternalPaths: allowedExternalPaths)
                    try executeMove(
                        source: sourceURL, destination: destURL,
                        rollback: &rollbackActions
                    )

                case .chmod:
                    let url = try validatedURL(path: step.path, root: rootPath, allowedExternalPaths: allowedExternalPaths)
                    try executeChmod(
                        url: url, mode: step.mode ?? "755",
                        rollback: &rollbackActions
                    )

                case .writeFile:
                    let url = try validatedURL(path: step.path, root: rootPath, allowedExternalPaths: allowedExternalPaths)
                    try executeWriteFile(
                        url: url, content: step.content ?? "",
                        rollback: &rollbackActions
                    )

                case .symlink:
                    guard let source = step.source else {
                        throw InstallStepError.missingSource(
                            action: step.action.rawValue, path: step.path
                        )
                    }
                    let sourceURL = try validatedURL(path: source, root: rootPath, allowedExternalPaths: allowedExternalPaths)
                    let linkURL = try validatedURL(path: step.path, root: rootPath, allowedExternalPaths: allowedExternalPaths)
                    try executeSymlink(
                        source: sourceURL, link: linkURL,
                        rollback: &rollbackActions
                    )

                case .generateSecret:
                    let secret = try executeGenerateSecret(step: step)
                    secrets[step.path] = secret
                    // Inject into context for subsequent steps
                    var updatedValues = currentContext.values
                    updatedValues[step.path] = secret
                    currentContext = TemplateContext(values: updatedValues)

                case .cleanup:
                    let url = try validatedURL(path: step.path, root: rootPath, allowedExternalPaths: allowedExternalPaths)
                    try executeCleanup(url: url)
                    // No rollback for cleanup — it's a terminal action
                }
            } catch let error as InstallStepError {
                try rollback(error)
            } catch {
                try rollback(InstallStepError.stepFailed(
                    action: step.action.rawValue,
                    path: step.path,
                    detail: error.localizedDescription
                ))
            }
        }

        log.info("[install-steps] All \(block.steps.count) steps completed successfully")
        return Result(generatedSecrets: secrets)
    }

    // MARK: - Path Validation

    private func validatedURL(path: String, root: String, allowedExternalPaths: Set<String>) throws -> URL {
        let url = URL(fileURLWithPath: path).standardizedFileURL

        // Reject path traversal
        guard !url.pathComponents.contains("..") else {
            throw InstallStepError.pathEscapesRoot(path: path, root: root)
        }

        // Must be inside service root OR match an allowed external path
        let normalized = url.path
        if !isPath(normalized, insideOrEqualTo: root) {
            let isAllowed = allowedExternalPaths.contains { allowed in
                isPath(normalized, insideOrEqualTo: allowed)
            }
            guard isAllowed else {
                throw InstallStepError.pathEscapesRoot(path: path, root: root)
            }
        }

        return url
    }

    private func isPath(_ path: String, insideOrEqualTo root: String) -> Bool {
        path == root || path.hasPrefix(root + "/")
    }

    // MARK: - Step Implementations

    private func executeMkdir(url: URL, rollback: inout [() -> Void]) throws {
        let existed = fileManager.fileExists(atPath: url.path)
        try fileManager.createDirectory(
            at: url, withIntermediateDirectories: true
        )
        if !existed {
            rollback.append { [fileManager] in
                try? fileManager.removeItem(at: url)
            }
        }
        log.debug("[install-steps] mkdir: \(url.path)")
    }

    private func executeCopy(
        source: URL, destination: URL,
        rollback: inout [() -> Void]
    ) throws {
        // Ensure parent exists
        let parent = destination.deletingLastPathComponent()
        try? fileManager.createDirectory(
            at: parent, withIntermediateDirectories: true
        )
        try fileManager.copyItem(at: source, to: destination)
        rollback.append { [fileManager] in
            try? fileManager.removeItem(at: destination)
        }
        log.debug("[install-steps] copy: \(source.path) -> \(destination.path)")
    }

    private func executeMove(
        source: URL, destination: URL,
        rollback: inout [() -> Void]
    ) throws {
        let parent = destination.deletingLastPathComponent()
        try? fileManager.createDirectory(
            at: parent, withIntermediateDirectories: true
        )
        try fileManager.moveItem(at: source, to: destination)
        // Rollback: move back
        rollback.append { [fileManager] in
            try? fileManager.moveItem(at: destination, to: source)
        }
        log.debug("[install-steps] move: \(source.path) -> \(destination.path)")
    }

    private func executeChmod(
        url: URL, mode: String,
        rollback: inout [() -> Void]
    ) throws {
        // Parse octal mode string
        guard let octalMode = UInt16(mode, radix: 8) else {
            throw InstallStepError.stepFailed(
                action: "chmod", path: url.path,
                detail: "Invalid mode '\(mode)' (expected octal, e.g. '755')."
            )
        }

        // Capture old permissions for rollback
        let attrs = try fileManager.attributesOfItem(atPath: url.path)
        let oldPerms = attrs[.posixPermissions] as? UInt16

        try fileManager.setAttributes(
            [.posixPermissions: NSNumber(value: octalMode)],
            ofItemAtPath: url.path
        )

        if let oldPerms {
            rollback.append { [fileManager] in
                try? fileManager.setAttributes(
                    [.posixPermissions: NSNumber(value: oldPerms)],
                    ofItemAtPath: url.path
                )
            }
        }
        log.debug("[install-steps] chmod \(mode): \(url.path)")
    }

    private func executeWriteFile(
        url: URL, content: String,
        rollback: inout [() -> Void]
    ) throws {
        let parent = url.deletingLastPathComponent()
        try? fileManager.createDirectory(
            at: parent, withIntermediateDirectories: true
        )

        let existed = fileManager.fileExists(atPath: url.path)
        let oldContent = existed ? fileManager.contents(atPath: url.path) : nil

        guard let data = content.data(using: .utf8) else {
            throw InstallStepError.stepFailed(
                action: "writeFile", path: url.path,
                detail: "Content could not be encoded as UTF-8."
            )
        }
        try data.write(to: url, options: .atomic)

        if existed, let oldContent {
            rollback.append { [fileManager] in
                try? oldContent.write(to: url, options: .atomic)
                _ = fileManager // keep reference
            }
        } else {
            rollback.append { [fileManager] in
                try? fileManager.removeItem(at: url)
            }
        }
        log.debug("[install-steps] writeFile: \(url.path) (\(data.count) bytes)")
    }

    private func executeSymlink(
        source: URL, link: URL,
        rollback: inout [() -> Void]
    ) throws {
        try fileManager.createSymbolicLink(
            at: link, withDestinationURL: source
        )
        rollback.append { [fileManager] in
            try? fileManager.removeItem(at: link)
        }
        log.debug("[install-steps] symlink: \(link.path) -> \(source.path)")
    }

    private func executeGenerateSecret(step: InstallStep) throws -> String {
        let byteLength = step.content.flatMap { Int($0) } ?? 32
        guard byteLength > 0 else {
            throw InstallStepError.stepFailed(
                action: "generateSecret", path: step.path,
                detail: "Byte length must be positive."
            )
        }

        var bytes = [UInt8](repeating: 0, count: byteLength)
        let status = SecRandomCopyBytes(kSecRandomDefault, byteLength, &bytes)
        guard status == errSecSuccess else {
            throw InstallStepError.stepFailed(
                action: "generateSecret", path: step.path,
                detail: "SecRandomCopyBytes failed with status \(status)."
            )
        }

        let data = Data(bytes)
        let encoded: String
        switch step.mode?.lowercased() {
        case "base64":
            encoded = data.base64EncodedString()
        default: // "hex" or nil
            encoded = data.map { String(format: "%02x", $0) }.joined()
        }

        log.debug("[install-steps] generateSecret: \(step.path) (\(byteLength) bytes, \(step.mode ?? "hex"))")
        // No rollback needed — secrets are ephemeral template variables
        return encoded
    }

    private func executeCleanup(url: URL) throws {
        guard fileManager.fileExists(atPath: url.path) else {
            log.debug("[install-steps] cleanup: \(url.path) (already gone)")
            return
        }
        try fileManager.removeItem(at: url)
        log.debug("[install-steps] cleanup: \(url.path)")
    }
}
