import Foundation

/// Deterministic path resolution for launchd plist files.
///
/// Haven writes per-user LaunchAgent plists so that services run in the
/// user's login session. This type computes the standard paths without
/// touching the filesystem.
///
/// ## Path conventions
///
/// ```
/// ~/Library/LaunchAgents/<label>.plist
/// ```
///
/// The label is generated by `LaunchdLabel` and follows the pattern
/// `app.haven.<capability-id>.<unit-id>`.
public struct LaunchdPaths: Equatable, Sendable {

    /// The LaunchAgents directory where plist files are written.
    public let launchAgentsDirectory: URL

    /// Creates paths rooted at the given LaunchAgents directory.
    ///
    /// - Parameter launchAgentsDirectory: The directory for plist files.
    ///   Defaults to `~/Library/LaunchAgents`.
    public init(launchAgentsDirectory: URL? = nil) {
        if let dir = launchAgentsDirectory {
            self.launchAgentsDirectory = dir
        } else {
            self.launchAgentsDirectory = LaunchdPaths.defaultLaunchAgentsDirectory
        }
    }

    /// The default LaunchAgents directory for the current user.
    public static var defaultLaunchAgentsDirectory: URL {
        FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent("Library")
            .appendingPathComponent("LaunchAgents")
    }

    /// Compute the plist file path for a given launchd label.
    ///
    /// - Parameter label: The launchd job label (e.g., `app.haven.cap.unit`).
    /// - Returns: The full path like `~/Library/LaunchAgents/app.haven.cap.unit.plist`.
    public func plistPath(for label: String) -> URL {
        launchAgentsDirectory.appendingPathComponent("\(label).plist")
    }
}
